apiVersion: v1
kind: Service
metadata:
  name: keel-web
  labels:
    app.kubernetes.io/name: keel-web
    app.kubernetes.io/part-of: keel
spec:
  selector:
    app.kubernetes.io/name: keel-web
  ports:
    - name: http
      port: 80
      targetPort: http
