apiVersion: v1
kind: Service
metadata:
  name: keel-server
  labels:
    app.kubernetes.io/name: keel-server
    app.kubernetes.io/part-of: keel
spec:
  selector:
    app.kubernetes.io/name: keel-server
  ports:
    - name: http
      port: 8000
      targetPort: http
