"""Identity domain: users, orgs, memberships, persisted Agents, grants (M3.6, WS-L)."""

from __future__ import annotations

from keel_core.identity.audit import (
    AuditAction,
    AuditEvent,
    AuditSink,
    InMemoryAuditSink,
    LoggingAuditSink,
)
from keel_core.identity.authz import AuthorizationService, AuthzDecision
from keel_core.identity.models import (
    ADMIN_ROLES,
    ROLE_CAPABILITIES,
    Agent,
    AgentKind,
    AgentStatus,
    Capability,
    ConflictError,
    CrossOrgError,
    GrantStatus,
    IdentityError,
    IdentityValidationError,
    LastOwnerError,
    Membership,
    MembershipRole,
    MembershipStatus,
    NotFoundError,
    OIDCIdentity,
    OptimisticConcurrencyError,
    Organization,
    OrganizationStatus,
    ResourceGrant,
    User,
    UserStatus,
    capabilities_for_role,
    new_agent_id,
    new_grant_id,
    new_membership_id,
    new_oidc_id,
    new_org_id,
    new_user_id,
    normalize_email,
    validate_agent_name,
    validate_display_name,
    validate_org_slug,
)
from keel_core.identity.oidc import (
    HTTPJWKSProvider,
    JWKSProvider,
    OIDCAvailabilityError,
    OIDCClaims,
    OIDCConfig,
    OIDCVerificationError,
    OIDCVerifier,
    StaticJWKSProvider,
)
from keel_core.identity.service import IdentityService, OrgContext
from keel_core.identity.store import (
    IdentityStore,
    InMemoryIdentityStore,
    PostgresIdentityStore,
)

__all__ = [
    "ADMIN_ROLES",
    "ROLE_CAPABILITIES",
    "Agent",
    "AgentKind",
    "AgentStatus",
    "AuditAction",
    "AuditEvent",
    "AuditSink",
    "AuthorizationService",
    "AuthzDecision",
    "Capability",
    "ConflictError",
    "CrossOrgError",
    "GrantStatus",
    "HTTPJWKSProvider",
    "IdentityError",
    "IdentityService",
    "IdentityStore",
    "IdentityValidationError",
    "InMemoryAuditSink",
    "InMemoryIdentityStore",
    "JWKSProvider",
    "LastOwnerError",
    "LoggingAuditSink",
    "Membership",
    "MembershipRole",
    "MembershipStatus",
    "NotFoundError",
    "OIDCClaims",
    "OIDCConfig",
    "OIDCAvailabilityError",
    "OIDCIdentity",
    "OIDCVerificationError",
    "OIDCVerifier",
    "OptimisticConcurrencyError",
    "OrgContext",
    "Organization",
    "OrganizationStatus",
    "PostgresIdentityStore",
    "ResourceGrant",
    "StaticJWKSProvider",
    "User",
    "UserStatus",
    "capabilities_for_role",
    "new_agent_id",
    "new_grant_id",
    "new_membership_id",
    "new_oidc_id",
    "new_org_id",
    "new_user_id",
    "normalize_email",
    "validate_agent_name",
    "validate_display_name",
    "validate_org_slug",
]
