"""Typed DTOs for the stable `/v1` Keel HTTP surface.

This intentionally small checked-in surface is generated by neither a network
service nor a codegen binary.  `scripts/check_openapi_compat.py` keeps it tied to
an additive-only OpenAPI contract.
"""

from __future__ import annotations

from pydantic import BaseModel


class CreateMessageRequest(BaseModel):
    """Request body for admitting a message to a session."""

    content: str
    idempotency_key: str | None = None


class CreateMessageResponse(BaseModel):
    """Accepted message/run acknowledgement."""

    session_id: str
    run_id: str
    accepted: bool = True


class InterruptRunResponse(BaseModel):
    """Result of an interrupt request."""

    ok: bool


# --- Identity (M3.6) — additive DTOs -------------------------------------------------


class UserSummary(BaseModel):
    """A durable identity user."""

    id: str
    display_name: str
    email: str | None = None
    status: str


class OrganizationSummary(BaseModel):
    """An organization (tenant)."""

    id: str
    slug: str
    display_name: str
    status: str


class MembershipSummary(BaseModel):
    """A user's membership + role in an org."""

    id: str
    org_id: str
    user_id: str
    role: str
    status: str


class OrganizationMembership(BaseModel):
    """An organization paired with the caller's membership in it."""

    organization: OrganizationSummary
    membership: MembershipSummary


class MeResponse(BaseModel):
    """The authenticated user and the organizations it belongs to."""

    user: UserSummary
    organizations: list[OrganizationMembership] = []


class AgentSummary(BaseModel):
    """A persisted personal/team Agent."""

    id: str
    org_id: str
    kind: str
    owner_user_id: str
    name: str
    persona: str
    status: str
    version: int


class GrantSummary(BaseModel):
    """An explicit Agent resource grant."""

    id: str
    org_id: str
    agent_id: str
    resource_type: str
    resource_id: str
    capability: str
    grantor_user_id: str
    status: str


class CreateOrganizationRequest(BaseModel):
    """Create an organization (the caller becomes its owner)."""

    slug: str
    display_name: str


class CreateAgentRequest(BaseModel):
    """Create a personal or team Agent in the selected org."""

    kind: str
    name: str
    persona: str = ""


class CreateGrantRequest(BaseModel):
    """Grant an Agent a capability on a resource."""

    agent_id: str
    resource_type: str
    resource_id: str
    capability: str


# --- Managed projects (M3.7) ---------------------------------------------------------


class ProjectSummary(BaseModel):
    """A managed, org-owned project."""

    id: str
    org_id: str
    slug: str
    display_name: str
    source: str
    visibility: str
    status: str
    default_branch: str
    github_repository_id: int | None = None
    version: int


class WorktreeSummary(BaseModel):
    """A run-scoped materialized worktree."""

    id: str
    org_id: str
    project_id: str
    run_id: str
    git_ref: str
    commit_sha: str | None = None
    status: str


class SyncEntrySummary(BaseModel):
    """One repo sync ledger entry."""

    id: str
    project_id: str
    kind: str
    status: str
    git_ref: str | None = None
    before_sha: str | None = None
    after_sha: str | None = None
    delivery_id: str | None = None


class InstallationSummary(BaseModel):
    """A GitHub App installation bound to an org."""

    id: str
    org_id: str
    installation_id: int
    app_id: int
    account_login: str
    account_type: str
    status: str


class RunAssociation(BaseModel):
    """The result of associating a durable run with a project."""

    run_id: str
    created: bool


class CreateProjectRequest(BaseModel):
    """Create a blank/local managed project."""

    slug: str
    display_name: str
    visibility: str = "private"
    default_branch: str = "main"


class ImportProjectRequest(BaseModel):
    """Import a project from a GitHub repository (via an installation)."""

    slug: str
    display_name: str
    installation_id: int
    repo_full_name: str


class UpdateProjectRequest(BaseModel):
    """Optimistically update a project's mutable fields."""

    expected_version: int
    display_name: str | None = None
    default_branch: str | None = None
    visibility: str | None = None


class MaterializeWorktreeRequest(BaseModel):
    """Materialize a run-scoped worktree."""

    run_id: str
    git_ref: str = "HEAD"
    agent_id: str | None = None


class AssociateRunRequest(BaseModel):
    """Associate a durable run with a project."""

    run_id: str
    agent_id: str | None = None


class GrantProjectRequest(BaseModel):
    """Grant an Agent a capability on a project."""

    agent_id: str
    capability: str


class LinkInstallationRequest(BaseModel):
    """Bind a GitHub App installation to the selected org."""

    installation_id: int
    app_id: int
    account_login: str
    account_type: str = "Organization"


# --- Read-only code review (WS-R) ----------------------------------------------------


class CreateReviewRequest(BaseModel):
    """Trigger a read-only review of a project branch/commit/PR."""

    source: str = "branch"
    head: str
    base: str | None = None
    model: str | None = None
    agent_id: str | None = None
    max_findings: int = 50
    idempotency_key: str | None = None


class CreateReviewResponse(BaseModel):
    """The durable review that was created (or matched by idempotency)."""

    review_id: str
    run_id: str
    status: str
    idempotency_key: str
    created: bool


class ReviewStatusSummary(BaseModel):
    """The status projection of a read-only review."""

    review_id: str
    org_id: str
    project_id: str
    run_id: str
    status: str
    source: str
    head: str
    base: str | None = None
    model: str
    created_at: str
    updated_at: str
    finding_count: int
    severity_counts: dict[str, int]
    prompt_tokens: int
    completion_tokens: int
    cost_usd: float
    report_json_sha256: str | None = None
    report_markdown_sha256: str | None = None
    error_kind: str | None = None
    error_message: str | None = None


# --- Durable IM (OneBot/Telegram) channel routing (M3.7) — additive DTOs -------------


class ImMappingPolicy(BaseModel):
    """A channel mapping's reply/tool policy (capability flags only — never a secret)."""

    reply_enabled: bool = True
    partial_replies: bool = False
    approvals_enabled: bool = False
    allow_tools: list[str] = []


class CreateImMappingRequest(BaseModel):
    """Create an org-owned IM channel mapping binding a chat to an Agent + scope + policy."""

    provider: str  # "onebot" | "telegram"
    external_bot_id: str
    external_chat_id: str
    chat_kind: str  # "personal" | "group"
    agent_id: str
    run_as_user_id: str  # the active org member the IM run executes as (not the platform admin)
    policy: ImMappingPolicy = ImMappingPolicy()


class ImMappingSummary(BaseModel):
    """An org-owned durable IM channel mapping (no raw external secrets)."""

    id: str
    org_id: str
    provider: str
    external_bot_id: str
    external_chat_id: str
    chat_kind: str
    agent_id: str
    scope_id: str
    run_as_user_id: str = ""
    policy: ImMappingPolicy
    status: str  # "active" | "disabled" | "revoked"
    version: int
    created_by: str
    revoked_by: str = ""
