"""Typed DTOs for the stable `/v1` Keel HTTP surface.

This intentionally small checked-in surface is generated by neither a network
service nor a codegen binary.  `scripts/check_openapi_compat.py` keeps it tied to
an additive-only OpenAPI contract.
"""

from __future__ import annotations

from pydantic import BaseModel


class CreateMessageRequest(BaseModel):
    """Request body for admitting a message to a session."""

    content: str
    idempotency_key: str | None = None


class CreateMessageResponse(BaseModel):
    """Accepted message/run acknowledgement."""

    session_id: str
    run_id: str
    accepted: bool = True


class InterruptRunResponse(BaseModel):
    """Result of an interrupt request."""

    ok: bool
