"""Controlled patch proposals + human-approved GitHub Draft PR writeback (WS-PP)."""

from __future__ import annotations

from .errors import (
    PatchApprovalError,
    PatchBoundsExceeded,
    PatchError,
    PatchLeaseLost,
    PatchNotFound,
    PatchPolicyViolation,
    PatchProviderError,
    PatchProviderUnavailable,
    PatchRemoteUnavailable,
    PatchStaleError,
    PatchStateError,
    PatchValidationError,
    PatchWritebackError,
)
from .models import (
    LEGAL_TRANSITIONS,
    TERMINAL_STATUSES,
    ChangedFile,
    ChangeKind,
    PatchBudget,
    PatchBundleManifest,
    PatchProposal,
    PatchProposalRequest,
    PatchRecord,
    PatchStatus,
    ProposalId,
    ProposedCommit,
    TestResult,
    TestStatus,
    can_transition,
    changed_path_digest,
    ensure_transition,
    is_forbidden_path,
    new_proposal_id,
    normalize_repo_path,
    run_branch_for,
    task_digest,
    validate_commit_sha,
    validate_run_branch,
)
from .outbox import (
    InMemoryPatchProposalOutbox,
    PatchOutboxEntry,
    PatchOutboxStatus,
    PatchProposalOutbox,
    PostgresPatchProposalOutbox,
)
from .store import ApprovalDraft

__all__ = [
    "LEGAL_TRANSITIONS",
    "TERMINAL_STATUSES",
    "ApprovalDraft",
    "ChangeKind",
    "ChangedFile",
    "InMemoryPatchProposalOutbox",
    "PatchApprovalError",
    "PatchBoundsExceeded",
    "PatchBudget",
    "PatchBundleManifest",
    "PatchError",
    "PatchLeaseLost",
    "PatchNotFound",
    "PatchOutboxEntry",
    "PatchOutboxStatus",
    "PatchPolicyViolation",
    "PatchProposal",
    "PatchProposalOutbox",
    "PatchProposalRequest",
    "PatchProviderError",
    "PatchProviderUnavailable",
    "PatchRecord",
    "PatchRemoteUnavailable",
    "PatchStaleError",
    "PatchStateError",
    "PatchStatus",
    "PatchValidationError",
    "PatchWritebackError",
    "PostgresPatchProposalOutbox",
    "ProposalId",
    "ProposedCommit",
    "TestResult",
    "TestStatus",
    "can_transition",
    "changed_path_digest",
    "ensure_transition",
    "is_forbidden_path",
    "new_proposal_id",
    "normalize_repo_path",
    "run_branch_for",
    "task_digest",
    "validate_commit_sha",
    "validate_run_branch",
]
