"""Trusted control-plane writeback: human-approved dedicated branch + GitHub Draft PR (WS-PP).

This is the *only* place a proposal's approved commit ever reaches a remote, and it runs entirely
on the control plane — never in the sandbox, and never before a human approval atomically queued
the writeback. For an approved proposal it:

1. **Re-verifies the base has not moved.** It reads the current sha of the approved base branch on
   the remote and fails closed (:class:`PatchStaleError`) if it no longer equals the exact base
   the proposal was generated + approved against. An old approval is *never* silently rebased onto
   a moved base.
2. **Verifies bundle/tree integrity.** The exact approved commit (pinned in the authoritative repo
   at generation time) is confirmed present and its tree matches the approved manifest.
3. **Pushes exactly the approved commit to a dedicated run branch** (validated namespace, never the
   default branch, no force, no tags, no ref deletion) via a JIT installation token handed to Git
   only through an environment ``http.extraHeader`` — the token never enters argv, config, a log,
   the sandbox, or an artifact.
4. **Opens an idempotent GitHub Draft PR** from the dedicated branch into the approved base branch
   with a bounded, generated body. It never merges, marks ready, comments, or pushes the default
   branch.

Crash recovery: both the push->PR and PR->DB windows are reconciled by detecting the existing exact
branch/PR (by sha / head) and reusing them instead of duplicating.
"""

from __future__ import annotations

import asyncio
import base64
import logging
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, Protocol

from keel_core.coding.local import LocalCodingStorage
from keel_core.coding.models import ProjectId
from keel_core.projects.github.client import GitHubError
from keel_core.projects.service import GitHubIntegration

from .errors import (
    PatchRemoteUnavailable,
    PatchStaleError,
    PatchWritebackError,
)
from .models import PatchBundleManifest, PatchProposal, validate_run_branch

logger = logging.getLogger("keel.patch.writeback")

MAX_PR_BODY_CHARS = 60_000


def _basic_auth_header(token: str) -> str:
    """A GitHub installation-token ``Authorization`` header (``x-access-token`` basic auth)."""
    if not token or "\r" in token or "\n" in token:
        raise PatchWritebackError("invalid installation token")
    encoded = base64.b64encode(f"x-access-token:{token}".encode()).decode("ascii")
    return f"Authorization: Basic {encoded}"


@dataclass(frozen=True, slots=True)
class WritebackTarget:
    """The remote repository binding a writeback pushes/opens a PR against."""

    full_name: str
    installation_id: int
    clone_url: str
    default_branch: str

    @property
    def owner(self) -> str:
        return self.full_name.split("/", 1)[0]


@dataclass(frozen=True, slots=True)
class WritebackResult:
    remote_branch: str
    head_sha: str
    pr_number: int
    pr_url: str
    pr_node_id: str
    reused_branch: bool
    reused_pr: bool


class PatchWritebackLedger(Protocol):
    """Append-only repo-writeback audit sink (one row per verify/push/PR step)."""

    async def record(
        self,
        *,
        proposal_id: str,
        org_id: str,
        project_id: str,
        step: str,
        status: str,
        before_sha: str | None = None,
        after_sha: str | None = None,
        remote_branch: str = "",
        pr_number: int | None = None,
        detail: Mapping[str, Any] | None = None,
    ) -> None: ...


class _NullLedger:
    async def record(self, **_kwargs: Any) -> None:  # noqa: D401 - no-op
        return None


def build_pr_body(proposal: PatchProposal, manifest: PatchBundleManifest) -> str:
    """A bounded, generated Draft-PR body linking the proposal/report/tests (no secrets/source)."""
    lines = [
        "Automated **draft** pull request generated by Keel from a human-approved patch proposal.",
        "",
        f"- Proposal: `{proposal.id}`",
        f"- Base: `{proposal.base_ref}` @ `{proposal.base_sha}`",
        f"- Changed files: {len(manifest.files)}",
        f"- Tests: {proposal.test_status.value}",
        f"- Bundle: `{proposal.bundle_sha256}`",
    ]
    if proposal.source_ref:
        lines.append(f"- Source finding/report: `{proposal.source_ref}`")
    lines += [
        "",
        "This PR is a draft awaiting human review. Keel will not merge it, mark it "
        "ready-for-review, comment on it, or push the default branch.",
    ]
    body = "\n".join(lines)
    return body[:MAX_PR_BODY_CHARS]


@dataclass
class PatchWritebackService:
    """Execute one approved proposal's control-plane writeback (idempotent + crash-recoverable)."""

    github: GitHubIntegration
    storage: LocalCodingStorage
    ledger: PatchWritebackLedger = _NullLedger()

    async def write(
        self,
        proposal: PatchProposal,
        *,
        project_handle: str,
        target: WritebackTarget,
        manifest: PatchBundleManifest,
    ) -> WritebackResult:
        run_branch = validate_run_branch(
            proposal.remote_branch, default_branch=target.default_branch
        )
        base_branch = proposal.base_ref
        head_sha = proposal.head_sha
        handle = ProjectId(project_handle)

        # 1) Mint the JIT installation token ONCE, on the control plane only.
        token = (await self.github.tokens.get_token(target.installation_id)).token

        # 2) Re-verify the approved base has not moved on the remote (fail closed if it has).
        try:
            base_ref = await self.github.client.get_ref(
                token=token, full_name=target.full_name, ref=f"heads/{base_branch}"
            )
        except GitHubError as exc:
            raise _as_remote_error(exc) from exc
        current_base = _ref_object_sha(base_ref)
        if current_base is None:
            raise PatchWritebackError("approved base branch no longer exists on the remote")
        if current_base != proposal.base_sha:
            await self.ledger.record(
                proposal_id=proposal.id,
                org_id=proposal.org_id,
                project_id=proposal.project_id,
                step="verify_base",
                status="stale",
                before_sha=proposal.base_sha,
                after_sha=current_base,
                remote_branch=run_branch,
            )
            raise PatchStaleError(
                "approved base moved on the remote; regeneration + re-approval required"
            )
        await self.ledger.record(
            proposal_id=proposal.id,
            org_id=proposal.org_id,
            project_id=proposal.project_id,
            step="verify_base",
            status="succeeded",
            before_sha=proposal.base_sha,
            after_sha=current_base,
            remote_branch=run_branch,
        )

        # 3) Verify the exact approved commit + tree are present in the authoritative repo.
        await asyncio.to_thread(self.storage.resolve_commit, handle, head_sha)
        if manifest.commits:
            expected_tree = manifest.commits[-1].tree_sha
            actual_tree = await asyncio.to_thread(self.storage.commit_tree, handle, head_sha)
            if actual_tree != expected_tree:
                raise PatchWritebackError("approved commit tree does not match the bundle manifest")

        # 4) Push the dedicated branch (idempotent: skip if it already points at head_sha).
        reused_branch = await self._ensure_branch(
            token=token,
            target=target,
            handle=handle,
            run_branch=run_branch,
            head_sha=head_sha,
            proposal=proposal,
        )

        # 5) Open an idempotent Draft PR (reconcile an existing one after a crash).
        pr, reused_pr = await self._ensure_draft_pr(
            token=token,
            target=target,
            run_branch=run_branch,
            base_branch=base_branch,
            proposal=proposal,
            manifest=manifest,
        )
        return WritebackResult(
            remote_branch=run_branch,
            head_sha=head_sha,
            pr_number=int(pr["number"]),
            pr_url=str(pr.get("html_url", "")),
            pr_node_id=str(pr.get("node_id", "")),
            reused_branch=reused_branch,
            reused_pr=reused_pr,
        )

    async def _ensure_branch(
        self,
        *,
        token: str,
        target: WritebackTarget,
        handle: ProjectId,
        run_branch: str,
        head_sha: str,
        proposal: PatchProposal,
    ) -> bool:
        try:
            existing = await self.github.client.get_ref(
                token=token, full_name=target.full_name, ref=f"heads/{run_branch}"
            )
        except GitHubError as exc:
            raise _as_remote_error(exc) from exc
        existing_sha = _ref_object_sha(existing)
        if existing_sha == head_sha:
            await self.ledger.record(
                proposal_id=proposal.id,
                org_id=proposal.org_id,
                project_id=proposal.project_id,
                step="push_branch",
                status="succeeded",
                after_sha=head_sha,
                remote_branch=run_branch,
                detail={"reused": True},
            )
            return True
        if existing_sha is not None and existing_sha != head_sha:
            # A DIFFERENT commit already occupies our dedicated branch — never force over it.
            raise PatchWritebackError("dedicated run branch already exists with a different commit")
        safe_url = self.github.safe_clone_url(target.clone_url, target.full_name)
        auth_header = _basic_auth_header(token)
        try:
            await asyncio.to_thread(
                self.storage.push_commit,
                handle,
                safe_url,
                head_sha,
                target_branch=run_branch,
                auth_header=auth_header,
            )
        except Exception as exc:  # noqa: BLE001 - surfaced as a writeback failure (no token in msg)
            await self.ledger.record(
                proposal_id=proposal.id,
                org_id=proposal.org_id,
                project_id=proposal.project_id,
                step="push_branch",
                status="failed",
                after_sha=head_sha,
                remote_branch=run_branch,
            )
            raise PatchWritebackError("failed to push the dedicated run branch") from exc
        await self.ledger.record(
            proposal_id=proposal.id,
            org_id=proposal.org_id,
            project_id=proposal.project_id,
            step="push_branch",
            status="succeeded",
            after_sha=head_sha,
            remote_branch=run_branch,
        )
        return False

    async def _ensure_draft_pr(
        self,
        *,
        token: str,
        target: WritebackTarget,
        run_branch: str,
        base_branch: str,
        proposal: PatchProposal,
        manifest: PatchBundleManifest,
    ) -> tuple[dict[str, Any], bool]:
        head = f"{target.owner}:{run_branch}"
        try:
            existing = await self.github.client.list_pull_requests(
                token=token, full_name=target.full_name, head=head
            )
        except GitHubError as exc:
            raise _as_remote_error(exc) from exc
        for pr in existing:
            if isinstance(pr.get("number"), int):
                await self.ledger.record(
                    proposal_id=proposal.id,
                    org_id=proposal.org_id,
                    project_id=proposal.project_id,
                    step="create_pr",
                    status="succeeded",
                    remote_branch=run_branch,
                    pr_number=int(pr["number"]),
                    detail={"reused": True},
                )
                return pr, True
        body = build_pr_body(proposal, manifest)
        title = f"Keel patch: {proposal.id}"
        try:
            pr = await self.github.client.create_pull_request(
                token=token,
                full_name=target.full_name,
                title=title,
                head=run_branch,
                base=base_branch,
                body=body,
                draft=True,
            )
        except GitHubError as exc:
            # A 422 usually means a PR for this head already exists — reconcile instead of failing.
            if exc.status_code == 422:
                recovered = await self.github.client.list_pull_requests(
                    token=token, full_name=target.full_name, head=head
                )
                for pr in recovered:
                    if isinstance(pr.get("number"), int):
                        return pr, True
            await self.ledger.record(
                proposal_id=proposal.id,
                org_id=proposal.org_id,
                project_id=proposal.project_id,
                step="create_pr",
                status="failed",
                remote_branch=run_branch,
            )
            raise _as_remote_error(exc) from exc
        await self.ledger.record(
            proposal_id=proposal.id,
            org_id=proposal.org_id,
            project_id=proposal.project_id,
            step="create_pr",
            status="succeeded",
            remote_branch=run_branch,
            pr_number=int(pr["number"]),
        )
        return pr, False


def _ref_object_sha(ref: Mapping[str, Any] | None) -> str | None:
    if not ref:
        return None
    obj = ref.get("object")
    if isinstance(obj, Mapping):
        sha = obj.get("sha")
        if isinstance(sha, str):
            return sha
    return None


def _as_remote_error(exc: GitHubError) -> Exception:
    if getattr(exc, "is_transient", False):
        return PatchRemoteUnavailable(
            "remote git/GitHub temporarily unavailable", retry_after=exc.retry_after
        )
    return PatchWritebackError("remote git/GitHub call failed")


__all__ = [
    "PatchWritebackLedger",
    "PatchWritebackService",
    "WritebackResult",
    "WritebackTarget",
    "build_pr_body",
]
