"""Contract tests for the real-sandbox ``docker-compose.yml`` (M3B).

These are deterministic, Docker-free checks that the standard Compose stack deploys an
*isolated, authenticated* sandbox execution boundary — not the old in-process preview and not
a surface-runnable fake. They parse the committed ``docker-compose.yml`` (PyYAML resolves the
anchors + merge keys exactly as Compose would) and assert the security contract:

* ``keel-server`` / ``keel-worker`` use the fail-closed ``sandbox`` backend, talk to the
  ``keel-sandbox`` executor, load the RPC secret from a read-only *file*, and never mount the
  sandbox workspace.
* ``keel-sandbox`` is hardened (non-root, read-only rootfs, all caps dropped,
  no-new-privileges), lives ONLY on the internal RPC network, and holds no datastore/provider
  credentials or project storage.
* The RPC shared secret is generated by a one-shot bootstrap into a dedicated volume — it is
  never hard-coded in the YAML or source.

No Docker daemon, image build, or network is required; this runs in the non-integration suite.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
import yaml

from keel_core.tools.rpc_auth import MIN_RPC_SECRET_BYTES

REPO_ROOT = Path(__file__).resolve().parents[2]
COMPOSE_PATH = REPO_ROOT / "docker-compose.yml"

# Services that run the control plane / tool wiring and therefore must load the RPC secret.
_SECRET_CONSUMERS = ("keel-server", "keel-worker", "keel-sandbox")
_CONTROL_PLANE = ("keel-server", "keel-worker")


def _parse_volume(entry: str) -> tuple[str, str, str]:
    """Split a short-form ``source:target[:mode]`` volume string."""
    parts = entry.split(":")
    if len(parts) == 2:
        return parts[0], parts[1], ""
    if len(parts) == 3:
        return parts[0], parts[1], parts[2]
    raise AssertionError(f"unexpected volume form: {entry!r}")


@pytest.fixture(scope="module")
def compose() -> dict:
    assert COMPOSE_PATH.exists(), "docker-compose.yml is missing"
    return yaml.safe_load(COMPOSE_PATH.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def compose_text() -> str:
    return COMPOSE_PATH.read_text(encoding="utf-8")


def test_top_level_shape(compose: dict) -> None:
    assert compose.get("name") == "keel"
    services = compose["services"]
    for name in (
        "postgres",
        "redis",
        "keel-secret-init",
        "keel-sandbox",
        "keel-server",
        "keel-worker",
    ):
        assert name in services, f"service {name} missing from compose"


def test_control_plane_uses_fail_closed_sandbox_backend(compose: dict) -> None:
    services = compose["services"]
    for name in _CONTROL_PLANE:
        env = services[name]["environment"]
        assert env.get("KEEL_EXECUTION_BACKEND") == "sandbox", name
        # Points at the dedicated executor over the internal RPC network.
        assert env.get("KEEL_SANDBOX_URL") == "http://keel-sandbox:8090", name
        # Secret comes from a file, never an inline value.
        assert env.get("KEEL_SANDBOX_RPC_SECRET_FILE"), name
        assert "KEEL_SANDBOX_RPC_SECRET" not in env, f"{name} must not inline the RPC secret"
        # No unsafe local-dev escape hatch enabled in the standard stack.
        assert env.get("KEEL_SANDBOX_RPC_LOCAL_TEST_MODE") in (None, "false", False), name
        assert "KEEL_TRUSTED_PREVIEW_ALLOW_UNSAFE_EXECUTION" not in env, name


def test_control_plane_does_not_mount_sandbox_workspace(compose: dict) -> None:
    services = compose["services"]
    for name in _CONTROL_PLANE:
        sources = {_parse_volume(v)[0] for v in services[name].get("volumes", [])}
        # The control plane never touches the sandbox's own workspace/namespace trees.
        assert "sandboxworkspace" not in sources, name
        assert "sandboxnamespaces" not in sources, name
        # It DOES mount the generated secret, read-only.
        secret_mounts = [
            _parse_volume(v)
            for v in services[name].get("volumes", [])
            if _parse_volume(v)[0] == "sandboxsecret"
        ]
        assert secret_mounts, f"{name} must mount the RPC secret volume"
        assert all(mode == "ro" for _, _, mode in secret_mounts), f"{name} secret must be ro"


def test_control_plane_on_both_networks(compose: dict) -> None:
    services = compose["services"]
    for name in _CONTROL_PLANE:
        nets = services[name].get("networks", [])
        assert set(nets) == {"default", "sandboxnet"}, f"{name} networks={nets}"


def test_control_plane_waits_for_sandbox_and_secret(compose: dict) -> None:
    services = compose["services"]
    for name in _CONTROL_PLANE:
        deps = services[name].get("depends_on", {})
        assert deps.get("keel-sandbox", {}).get("condition") == "service_healthy", name
        assert (
            deps.get("keel-secret-init", {}).get("condition") == "service_completed_successfully"
        ), name


def test_sandbox_container_is_hardened(compose: dict) -> None:
    sandbox = compose["services"]["keel-sandbox"]
    assert sandbox["read_only"] is True
    assert sandbox["cap_drop"] == ["ALL"]
    assert "no-new-privileges:true" in sandbox["security_opt"]
    assert str(sandbox["user"]).startswith("10100")  # non-root
    assert sandbox["build"]["dockerfile"] == "deploy/docker/sandbox.Dockerfile"
    # tmpfs scratch so a read-only rootfs still has writable /tmp.
    assert any("/tmp" in t for t in sandbox.get("tmpfs", []))


def test_sandbox_only_on_internal_network(compose: dict) -> None:
    sandbox = compose["services"]["keel-sandbox"]
    assert sandbox.get("networks") == ["sandboxnet"], "sandbox must be on the internal net ONLY"


def test_sandbox_holds_no_datastore_or_provider_credentials(compose: dict) -> None:
    env = compose["services"]["keel-sandbox"]["environment"]
    forbidden = ("DATABASE", "REDIS", "GITHUB", "OPENAI", "ANTHROPIC", "GEMINI", "OLLAMA")
    leaked = [k for k in env if any(tok in k.upper() for tok in forbidden)]
    assert not leaked, f"sandbox must hold no datastore/provider creds, found: {leaked}"


def test_sandbox_writable_mounts_are_only_its_own_trees(compose: dict) -> None:
    sandbox = compose["services"]["keel-sandbox"]
    writable, readonly = [], []
    for entry in sandbox["volumes"]:
        source, _, mode = _parse_volume(entry)
        (readonly if mode == "ro" else writable).append(source)
    # Only the sandbox's own workspace + namespace trees are writable.
    assert set(writable) == {"sandboxworkspace", "sandboxnamespaces"}, writable
    # The secret is present and read-only.
    assert readonly == ["sandboxsecret"], readonly
    # Never the shared project storage, and never a host bind mount of the repo/.git/.env.
    assert "projectdata" not in writable and "projectdata" not in readonly
    for entry in sandbox["volumes"]:
        assert not entry.startswith("."), f"no host bind mount into sandbox: {entry}"
        assert not entry.startswith("/"), f"no host bind mount into sandbox: {entry}"


def test_sandbox_asserts_isolation_but_keeps_shell_denied(compose: dict) -> None:
    env = compose["services"]["keel-sandbox"]["environment"]
    # Honest: only the workspace/namespace trees are mounted, so the isolation floor is real.
    assert env.get("KEEL_SANDBOX_ISOLATION_VERIFIED") == "true"
    # But shell stays fail-closed: neither faked-isolation flag is set, so file ops work while
    # command execution is denied (see docker-compose.yml honest-scope note).
    assert "KEEL_SANDBOX_WORKSPACE_SANITIZED" not in env
    assert "KEEL_SANDBOX_NAMESPACE_SHELL_ISOLATED" not in env


def test_sandbox_exposes_unauthenticated_liveness_only(compose: dict) -> None:
    sandbox = compose["services"]["keel-sandbox"]
    test_cmd = " ".join(sandbox["healthcheck"]["test"])
    assert "/health" in test_cmd, "liveness probes the unauthenticated /health endpoint"
    # The healthcheck must not smuggle the secret onto argv.
    assert "SECRET" not in test_cmd.upper()


def test_secret_init_generates_strong_secret_without_hardcoding(compose: dict) -> None:
    init = compose["services"]["keel-secret-init"]
    assert init.get("restart") == "no", "secret bootstrap is one-shot"
    sources = {_parse_volume(v)[0] for v in init["volumes"]}
    assert sources == {"sandboxsecret"}, "secret init only touches the secret volume"
    script = "\n".join(init["command"]) if isinstance(init["command"], list) else init["command"]
    assert "token_urlsafe" in script, "secret must be randomly generated"
    # token_urlsafe(n) yields ~1.3*n url-safe chars == that many bytes; assert the requested
    # entropy comfortably exceeds the RPC minimum.
    match = re.search(r"token_urlsafe\((\d+)\)", script)
    assert match, "could not find token_urlsafe(n) call"
    assert int(match.group(1)) >= MIN_RPC_SECRET_BYTES, "generated secret too short"
    assert "chmod" in script, "secret file is made read-only after write"


def test_no_hardcoded_rpc_secret_anywhere(compose_text: str) -> None:
    # There must be no inline ``KEEL_SANDBOX_RPC_SECRET: <value>`` (only the _FILE reference).
    inline = re.search(r"KEEL_SANDBOX_RPC_SECRET\s*:\s*\S", compose_text)
    assert inline is None, "no inline RPC secret may appear in docker-compose.yml"


def test_sandbox_network_is_internal(compose: dict) -> None:
    networks = compose["networks"]
    assert "default" in networks
    assert networks["sandboxnet"]["internal"] is True, "sandboxnet must be internal (no egress)"
    # Datastores/ollama must NOT join the internal RPC net (no control-plane data path).
    for name in ("postgres", "redis", "ollama"):
        assert "networks" not in compose["services"][name] or (
            "sandboxnet" not in compose["services"][name]["networks"]
        ), f"{name} must not be on sandboxnet"


def test_no_shared_exec_volume_remains(compose: dict) -> None:
    volumes = compose.get("volumes", {})
    # The old shared in-process exec volume is gone; the sandbox owns its trees.
    assert "execdata" not in volumes
    for expected in ("sandboxworkspace", "sandboxnamespaces", "sandboxsecret"):
        assert expected in volumes, f"volume {expected} must be declared"


def test_all_sandbox_stack_services_share_profiles(compose: dict) -> None:
    services = compose["services"]
    for name in _SECRET_CONSUMERS + ("keel-secret-init",):
        profiles = set(services[name].get("profiles", []))
        assert {"dev", "full"} <= profiles, f"{name} profiles={profiles}"
